sudo: false
language: php
env:
  global:
  - secure: "Jp85Caf738ippnEHji6dGSRIj0CoIOreYJqwtletrqtz1+EknF4k8lUVjHz6Ul0GDT9cC+X2SOicdP+wHqaItZqY7Kl9PjbHnPxDY4NUX8HCnwpobBkd9PdcJVgElrrgi698M1LyzZkQZUUkhoe2G8ZCznLJDgL6WzItMfAPHNpweLCNAKzG3tllu0l19TjDmVT615VgXItFGwL/jUc4YJRyKdBmGkBbVPm7t87ewYbTymswoPgZRwg670GvqUy47RsHUrxkyR2bTSMrbDRtI8SX+Eg3jx0yAS+WXtUZ2UhYJ1HlsPiozAY9Q/h3zf+2aABcTjEY6xe4x5BJ0zIFIroabfsroDzf3F51m/+5ZXFGIlLS660TmJ0/QC1nahl92O/2iFyPUt0a25E4rMzgaCsglRvxvYU4Ln6LiUKeIoeSxqy6BrJbS55LGornVeToXPVsjYFEpfuGepGUmHKUD7eI/z7OsuuyowAXJCn7GoZmWGVk4JGnTlRRLehjSJvLVQnHrTVJ+RQRSGrM46CKJSpobFMGwJBMjLVX2LH+moncmwNI4uxway9E9aKBKJ4d5KQ95+6SGkEM6T/Vzy8WaJ+K+OktJPBAaLFMiQH7TtEOPtS2f/M2IaJ7PYn5vAx2q0ADSSQH8fPX8hKQJEUXHIdrCMplF00swhiHIC7aUYs="
  - UPDATE_CROWDIN="no"

matrix:
  include:
  - php: 7.0
    env: UPDATE_CROWDIN="yes"

after_success:
  - if [[ $UPDATE_CROWDIN == "yes" && $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then vendor/bin/crowdin --upload; fi
