project_identifier: joomla-patchtester
api_key_env: 'CROWDIN_API_KEY'
base_path: ./language

files:
  -
    source: /en-GB/en-GB.plg_content_joomlarrssb.ini
    translation: /%locale%/%locale%.plg_content_joomlarrssb.ini
  -
    source: /en-GB/en-GB.plg_content_joomlarrssb.sys.ini
    translation: /%locale%/%locale%.plg_content_joomlarrssb.sys.ini
